### ISSUE TITLE
Crash when destroying chest next to auto assembler.

### ISSUE THREAD

**Issue by codewarrior0** [AnimeniacYuuto/EnhancedInventories#53]
Using version 1.1.8 of EnhancedInventories in a single-player game with the Regrowth modpack.

Auto assembler has a schematic loaded, redstone control set to "Disabled". Breaking a chest placed next to the assembler yields this crash:

```
Description: Ticking memory connection

java.lang.ClassCastException: net.minecraft.block.BlockAir cannot be cast to net.minecraft.block.BlockChest
	at yuuto.enhancedinventories.tile.TileAutoAssembler$$anonfun$updateSubInventoriesCache$1.apply(TileAutoAssembler.scala:106)
	at yuuto.enhancedinventories.tile.TileAutoAssembler$$anonfun$updateSubInventoriesCache$1.apply(TileAutoAssembler.scala:102)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at yuuto.enhancedinventories.tile.TileAutoAssembler.updateSubInventoriesCache(TileAutoAssembler.scala:102)
	at yuuto.enhancedinventories.block.BlockAutoAssembler.onNeighborChange(BlockAutoAssembler.scala:58)
```

**Comment by AnimeniacYuuto** [comment]
should be fixed as of b38d62de1a54b8238afabe302fe0a65fa1777c07
